trigger: none

pool: 'Private Agent'

# Define variables if needed
variables:
  environmentName: 'Pre-Production'

# Define stages and jobs
jobs:
- deployment: DeployToPreProduction
  displayName: 'Deploy to PreProduction'
  environment:
    name: $(environmentName)
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Create a folder in C drive
              New-Item -ItemType Directory -Path "C:\MyFolder"

          displayName: 'Create Folder in C Drive'
